import React, { createContext, useContext, useState } from 'react';

const base = {
  appTagline: 'Har dukaan, har service – ek jagah',
  selectLanguage: 'Select Language',
  chooseLanguage: 'Choose your preferred language',
  continue: 'Continue',
  greeting_morning: 'Good morning',
  greeting_afternoon: 'Good afternoon',
  greeting_evening: 'Good evening',
  nearbyServices: 'Nearby Services',
  searchPlaceholder: 'Search services, shops...',
  categories: 'Categories',
  allCategories: 'All',
  subscribeToUnlock: 'Subscribe to unlock',
  unlockToContact: 'Unlock to Contact',
  callNow: 'Call',
  whatsapp: 'WhatsApp',
  directions: 'Directions',
  bookService: 'Book Service',
  reviews: 'Reviews',
  services: 'Services',
  sendOtp: 'Send OTP',
  verifyLogin: 'Verify & Login',
  iAm: 'I am a',
  customer: 'Customer',
  provider: 'Provider',
  fullName: 'Full Name',
  phoneNumber: 'Phone Number',
  enterOtp: 'Enter OTP',
  myProfile: 'My Profile',
  logout: 'Logout',
  subscribe: 'Subscribe',
  choosePlan: 'Choose a Plan',
  unlockFullAccess: 'Unlock Full Access',
  aadhaarVerification: 'Aadhaar Verification',
  enterAadhaar: 'Enter Aadhaar Number',
  verifyAadhaar: 'Verify Aadhaar',
  shopDetails: 'Shop Details',
  setupStore: 'Setup Store',
  createStore: 'Create Store',
  shopName: 'Shop Name',
  category: 'Category',
  description: 'Description',
  location: 'Location',
  useGps: 'Use GPS',
  openNow: 'Open Now',
  closed: 'Closed',
  negotiable: 'Negotiable',
  back: 'Back',
  cancel: 'Cancel',
  confirm: 'Confirm',
  loading: 'Loading...',
  noShopsNearby: 'No shops found nearby',
  internetCheck: 'Check your internet connection',
  retry: 'Retry',
  saved: 'Saved',
  save: 'Save',
  emergency: 'Emergency',
  offers: 'Offers & Deals',
  iAmA: 'I am a',
  userDesc: 'Discover services near you',
  providerDesc: 'Grow your business',
  welcomeBack: 'Welcome back!',
  loginToContinue: 'Login to continue',
  searchLanguage: 'Search language...',
};

const translations = {
  en: base,
  hi: {
    ...base,
    appTagline: 'हर दुकान, हर सर्विस – एक जगह',
    selectLanguage: 'भाषा चुनें',
    chooseLanguage: 'अपनी पसंदीदा भाषा चुनें',
    continue: 'जारी रखें',
    greeting_morning: 'सुप्रभात',
    greeting_afternoon: 'नमस्ते',
    greeting_evening: 'शुभ संध्या',
    nearbyServices: 'नज़दीकी सेवाएं',
    searchPlaceholder: 'सेवाएं, दुकान खोजें...',
    categories: 'श्रेणियां',
    allCategories: 'सभी',
    subscribeToUnlock: 'अनलॉक के लिए सब्सक्राइब करें',
    unlockToContact: 'संपर्क अनलॉक करें',
    callNow: 'कॉल करें',
    whatsapp: 'व्हाट्सएप',
    directions: 'दिशा',
    bookService: 'बुक करें',
    reviews: 'समीक्षाएं',
    services: 'सेवाएं',
    sendOtp: 'OTP भेजें',
    verifyLogin: 'वेरिफाई करें',
    iAm: 'मैं हूं',
    customer: 'ग्राहक',
    provider: 'सेवा प्रदाता',
    fullName: 'पूरा नाम',
    phoneNumber: 'फ़ोन नंबर',
    enterOtp: 'OTP दर्ज करें',
    myProfile: 'मेरी प्रोफाइल',
    logout: 'लॉग आउट',
    subscribe: 'सब्सक्राइब',
    choosePlan: 'प्लान चुनें',
    unlockFullAccess: 'पूरी पहुंच अनलॉक करें',
    setupStore: 'दुकान सेटअप',
    createStore: 'दुकान बनाएं',
    shopName: 'दुकान का नाम',
    category: 'श्रेणी',
    description: 'विवरण',
    location: 'स्थान',
    useGps: 'GPS उपयोग करें',
    openNow: 'अभी खुला',
    closed: 'बंद',
    back: 'वापस',
    cancel: 'रद्द करें',
    confirm: 'पुष्टि करें',
    loading: 'लोड हो रहा है...',
    noShopsNearby: 'नज़दीक कोई दुकान नहीं मिली',
    retry: 'पुनः प्रयास',
    saved: 'सहेजा',
    save: 'सहेजें',
    emergency: 'आपातकाल',
    offers: 'ऑफर और डील',
    userDesc: 'पास की सेवाएं खोजें',
    providerDesc: 'अपना व्यापार बढ़ाएं',
    welcomeBack: 'वापसी पर स्वागत!',
    loginToContinue: 'जारी रखने के लिए लॉगिन करें',
    searchLanguage: 'भाषा खोजें...',
  },
  mr: {
    ...base,
    appTagline: 'हर दुकान, हर सेवा – एक ठिकाण',
    selectLanguage: 'भाषा निवडा',
    chooseLanguage: 'तुमची पसंतीची भाषा निवडा',
    continue: 'पुढे जा',
    greeting_morning: 'सुप्रभात',
    greeting_afternoon: 'नमस्कार',
    greeting_evening: 'शुभ संध्याकाळ',
    nearbyServices: 'जवळच्या सेवा',
    searchPlaceholder: 'सेवा, दुकान शोधा...',
    categories: 'श्रेण्या',
    allCategories: 'सर्व',
    unlockToContact: 'संपर्क अनलॉक करा',
    callNow: 'कॉल करा',
    sendOtp: 'OTP पाठवा',
    verifyLogin: 'सत्यापित करा',
    iAm: 'मी आहे',
    customer: 'ग्राहक',
    provider: 'सेवा प्रदाता',
    fullName: 'पूर्ण नाव',
    phoneNumber: 'फोन नंबर',
    logout: 'लॉग आउट',
    choosePlan: 'प्लान निवडा',
    loading: 'लोड होत आहे...',
    noShopsNearby: 'जवळ कोणतेही दुकान सापडले नाही',
    retry: 'पुन्हा प्रयत्न करा',
    emergency: 'आपत्कालीन',
    offers: 'ऑफर आणि सवलती',
    userDesc: 'जवळच्या सेवा शोधा',
    providerDesc: 'तुमचा व्यवसाय वाढवा',
    searchLanguage: 'भाषा शोधा...',
  },
  gu: {
    ...base,
    appTagline: 'દરેક દુકાન, દરેક સેવા – એક જ જગ્યા',
    selectLanguage: 'ભાષા પસંદ કરો',
    chooseLanguage: 'તમારી પસંદીદા ભાષા પસંદ કરો',
    continue: 'આગળ વધો',
    greeting_morning: 'સુપ્રભાત',
    greeting_afternoon: 'નમસ્તે',
    greeting_evening: 'શુભ સંધ્યા',
    nearbyServices: 'નજીકની સેવાઓ',
    searchPlaceholder: 'સેવાઓ, દુકાન શોધો...',
    categories: 'શ્રેણીઓ',
    allCategories: 'બધા',
    unlockToContact: 'સંપર્ક અનલૉક કરો',
    callNow: 'કૉલ',
    sendOtp: 'OTP મોકલો',
    verifyLogin: 'ચકાસો',
    iAm: 'હું છું',
    customer: 'ગ્રાહક',
    provider: 'સેવા પ્રદાતા',
    fullName: 'પૂરું નામ',
    phoneNumber: 'ફોન નંબર',
    logout: 'લૉગ આઉટ',
    choosePlan: 'પ્લાન પસંદ કરો',
    loading: 'લોડ થઈ રહ્યું છે...',
    noShopsNearby: 'નજીક કોઈ દુકાન મળી નથી',
    retry: 'ફરી પ્રયાસ',
    emergency: 'કટોકટી',
    offers: 'ઑફર અને ડીલ',
    userDesc: 'નજીકની સેવાઓ શોધો',
    providerDesc: 'તમારો વ્યવસાય વધારો',
    searchLanguage: 'ભાષા શોધો...',
  },
  te: {
    ...base,
    appTagline: 'ప్రతి దుకాణం, ప్రతి సేవ – ఒకే చోట',
    selectLanguage: 'భాష ఎంచుకోండి',
    chooseLanguage: 'మీకు నచ్చిన భాష ఎంచుకోండి',
    continue: 'కొనసాగించండి',
    greeting_morning: 'శుభోదయం',
    greeting_afternoon: 'నమస్కారం',
    greeting_evening: 'శుభ సాయంత్రం',
    nearbyServices: 'దగ్గర సేవలు',
    searchPlaceholder: 'సేవలు, దుకాణాలు వెతకండి...',
    categories: 'వర్గాలు',
    allCategories: 'అన్నీ',
    unlockToContact: 'సంప్రదించడానికి అన్‌లాక్ చేయండి',
    callNow: 'కాల్',
    sendOtp: 'OTP పంపండి',
    verifyLogin: 'నిర్ధారించండి',
    iAm: 'నేను',
    customer: 'కస్టమర్',
    provider: 'సేవా ప్రదాత',
    fullName: 'పూర్తి పేరు',
    phoneNumber: 'ఫోన్ నంబర్',
    logout: 'లాగ్ అవుట్',
    choosePlan: 'ప్లాన్ ఎంచుకోండి',
    loading: 'లోడ్ అవుతోంది...',
    noShopsNearby: 'దగ్గర దుకాణాలు కనుగొనబడలేదు',
    retry: 'మళ్ళీ ప్రయత్నించండి',
    emergency: 'అత్యవసరం',
    offers: 'ఆఫర్లు & డీల్స్',
    userDesc: 'దగ్గర సేవలు కనుగొనండి',
    providerDesc: 'మీ వ్యాపారాన్ని పెంచండి',
    searchLanguage: 'భాష వెతకండి...',
  },
  ta: {
    ...base,
    appTagline: 'எல்லா கடையும், எல்லா சேவையும் – ஒரே இடத்தில்',
    selectLanguage: 'மொழி தேர்வு',
    chooseLanguage: 'உங்கள் மொழியை தேர்ந்தெடுங்கள்',
    continue: 'தொடரவும்',
    greeting_morning: 'காலை வணக்கம்',
    greeting_afternoon: 'மதிய வணக்கம்',
    greeting_evening: 'மாலை வணக்கம்',
    nearbyServices: 'அருகிலுள்ள சேவைகள்',
    searchPlaceholder: 'சேவைகள், கடைகள் தேடுக...',
    categories: 'வகைகள்',
    allCategories: 'அனைத்தும்',
    unlockToContact: 'தொடர்பு கொள்ள அன்லாக் செய்க',
    callNow: 'அழைப்பு',
    sendOtp: 'OTP அனுப்பு',
    verifyLogin: 'சரிபார்க்கவும்',
    iAm: 'நான்',
    customer: 'வாடிக்கையாளர்',
    provider: 'சேவை வழங்குநர்',
    fullName: 'முழு பெயர்',
    phoneNumber: 'தொலைபேசி எண்',
    logout: 'வெளியேறு',
    choosePlan: 'திட்டம் தேர்வு',
    loading: 'ஏற்றுகிறது...',
    noShopsNearby: 'அருகில் கடைகள் இல்லை',
    retry: 'மீண்டும் முயற்சி',
    emergency: 'அவசரநிலை',
    offers: 'சலுகைகள்',
    userDesc: 'அருகிலுள்ள சேவைகளை கண்டறியுங்கள்',
    providerDesc: 'உங்கள் வணிகத்தை வளர்க்கவும்',
    searchLanguage: 'மொழி தேடுக...',
  },
  bn: {
    ...base,
    appTagline: 'প্রতিটি দোকান, প্রতিটি সেবা – একটি জায়গায়',
    selectLanguage: 'ভাষা নির্বাচন করুন',
    chooseLanguage: 'আপনার পছন্দের ভাষা নির্বাচন করুন',
    continue: 'চালিয়ে যান',
    greeting_morning: 'সুপ্রভাত',
    greeting_afternoon: 'নমস্কার',
    greeting_evening: 'শুভ সন্ধ্যা',
    nearbyServices: 'কাছের সেবা',
    searchPlaceholder: 'সেবা, দোকান খুঁজুন...',
    categories: 'বিভাগসমূহ',
    allCategories: 'সব',
    unlockToContact: 'যোগাযোগ আনলক করুন',
    callNow: 'কল',
    sendOtp: 'OTP পাঠান',
    verifyLogin: 'যাচাই করুন',
    iAm: 'আমি',
    customer: 'গ্রাহক',
    provider: 'সেবা প্রদানকারী',
    fullName: 'পুরো নাম',
    phoneNumber: 'ফোন নম্বর',
    logout: 'লগ আউট',
    choosePlan: 'পরিকল্পনা বেছে নিন',
    loading: 'লোড হচ্ছে...',
    noShopsNearby: 'কাছে কোন দোকান পাওয়া যায়নি',
    retry: 'আবার চেষ্টা করুন',
    emergency: 'জরুরী',
    offers: 'অফার এবং ডিল',
    userDesc: 'কাছের সেবা খুঁজুন',
    providerDesc: 'আপনার ব্যবসা বাড়ান',
    searchLanguage: 'ভাষা খুঁজুন...',
  },
  pa: {
    ...base,
    appTagline: 'ਹਰ ਦੁਕਾਨ, ਹਰ ਸੇਵਾ – ਇੱਕ ਥਾਂ',
    selectLanguage: 'ਭਾਸ਼ਾ ਚੁਣੋ',
    chooseLanguage: 'ਆਪਣੀ ਪਸੰਦੀਦਾ ਭਾਸ਼ਾ ਚੁਣੋ',
    continue: 'ਜਾਰੀ ਰੱਖੋ',
    greeting_morning: 'ਸ਼ੁਭ ਸਵੇਰ',
    greeting_afternoon: 'ਸਤ ਸ੍ਰੀ ਅਕਾਲ',
    greeting_evening: 'ਸ਼ੁਭ ਸ਼ਾਮ',
    nearbyServices: 'ਨੇੜੇ ਸੇਵਾਵਾਂ',
    searchPlaceholder: 'ਸੇਵਾਵਾਂ, ਦੁਕਾਨਾਂ ਖੋਜੋ...',
    categories: 'ਸ਼੍ਰੇਣੀਆਂ',
    allCategories: 'ਸਾਰੇ',
    unlockToContact: 'ਸੰਪਰਕ ਅਨਲੌਕ ਕਰੋ',
    callNow: 'ਕਾਲ',
    sendOtp: 'OTP ਭੇਜੋ',
    verifyLogin: 'ਪੁਸ਼ਟੀ ਕਰੋ',
    iAm: 'ਮੈਂ ਹਾਂ',
    customer: 'ਗਾਹਕ',
    provider: 'ਸੇਵਾ ਪ੍ਰਦਾਤਾ',
    fullName: 'ਪੂਰਾ ਨਾਮ',
    phoneNumber: 'ਫ਼ੋਨ ਨੰਬਰ',
    logout: 'ਲੌਗ ਆਉਟ',
    choosePlan: 'ਪਲਾਨ ਚੁਣੋ',
    loading: 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',
    noShopsNearby: 'ਨੇੜੇ ਕੋਈ ਦੁਕਾਨ ਨਹੀਂ ਮਿਲੀ',
    retry: 'ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ',
    emergency: 'ਐਮਰਜੈਂਸੀ',
    offers: 'ਆਫ਼ਰ ਅਤੇ ਡੀਲ',
    userDesc: 'ਨੇੜੇ ਸੇਵਾਵਾਂ ਲੱਭੋ',
    providerDesc: 'ਆਪਣਾ ਕਾਰੋਬਾਰ ਵਧਾਓ',
    searchLanguage: 'ਭਾਸ਼ਾ ਖੋਜੋ...',
  },
  kn: {
    ...base,
    appTagline: 'ಪ್ರತಿ ಅಂಗಡಿ, ಪ್ರತಿ ಸೇವೆ – ಒಂದೇ ಸ್ಥಳದಲ್ಲಿ',
    selectLanguage: 'ಭಾಷೆ ಆಯ್ಕೆ ಮಾಡಿ',
    chooseLanguage: 'ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭಾಷೆ ಆಯ್ಕೆ ಮಾಡಿ',
    continue: 'ಮುಂದುವರೆಯಿರಿ',
    greeting_morning: 'ಶುಭೋದಯ',
    greeting_afternoon: 'ನಮಸ್ಕಾರ',
    greeting_evening: 'ಶುಭ ಸಂಜೆ',
    nearbyServices: 'ಹತ್ತಿರದ ಸೇವೆಗಳು',
    searchPlaceholder: 'ಸೇವೆಗಳು, ಅಂಗಡಿಗಳು ಹುಡುಕಿ...',
    categories: 'ವರ್ಗಗಳು',
    allCategories: 'ಎಲ್ಲಾ',
    unlockToContact: 'ಸಂಪರ್ಕಕ್ಕೆ ಅನ್‌ಲಾಕ್ ಮಾಡಿ',
    callNow: 'ಕರೆ',
    sendOtp: 'OTP ಕಳುಹಿಸಿ',
    verifyLogin: 'ಪರಿಶೀಲಿಸಿ',
    iAm: 'ನಾನು',
    customer: 'ಗ್ರಾಹಕ',
    provider: 'ಸೇವಾ ಪೂರೈಕೆದಾರ',
    fullName: 'ಪೂರ್ಣ ಹೆಸರು',
    phoneNumber: 'ಫೋನ್ ಸಂಖ್ಯೆ',
    logout: 'ಲಾಗ್ ಔಟ್',
    choosePlan: 'ಯೋಜನೆ ಆಯ್ಕೆ',
    loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    noShopsNearby: 'ಹತ್ತಿರ ಅಂಗಡಿಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
    retry: 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
    emergency: 'ತುರ್ತು',
    offers: 'ಆಫರ್‌ಗಳು',
    userDesc: 'ಹತ್ತಿರದ ಸೇವೆಗಳನ್ನು ಹುಡುಕಿ',
    providerDesc: 'ನಿಮ್ಮ ವ್ಯವಹಾರ ಬೆಳೆಸಿ',
    searchLanguage: 'ಭಾಷೆ ಹುಡುಕಿ...',
  },
  ml: {
    ...base,
    appTagline: 'എല്ലാ കടകളും, എല്ലാ സേവനങ്ങളും – ഒരിടത്ത്',
    selectLanguage: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    chooseLanguage: 'നിങ്ങൾക്ക് ഇഷ്ടമുള്ള ഭാഷ തിരഞ്ഞെടുക്കുക',
    continue: 'തുടരുക',
    greeting_morning: 'ശുഭോദയം',
    greeting_afternoon: 'നമസ്കാരം',
    greeting_evening: 'ശുഭ സന്ധ്യ',
    nearbyServices: 'അടുത്തുള്ള സേവനങ്ങൾ',
    searchPlaceholder: 'സേവനങ്ങൾ, കടകൾ തിരയുക...',
    categories: 'വിഭാഗങ്ങൾ',
    allCategories: 'എല്ലാം',
    unlockToContact: 'ബന്ധപ്പെടാൻ അൺലോക്ക് ചെയ്യുക',
    callNow: 'വിളിക്കുക',
    sendOtp: 'OTP അയക്കുക',
    verifyLogin: 'സ്ഥിരീകരിക്കുക',
    iAm: 'ഞാൻ',
    customer: 'ഉപഭോക്താവ്',
    provider: 'സേവന ദാതാവ്',
    fullName: 'പൂർണ്ണ പേര്',
    phoneNumber: 'ഫോൺ നമ്പർ',
    logout: 'ലോഗ് ഔട്ട്',
    choosePlan: 'പ്ലാൻ തിരഞ്ഞെടുക്കുക',
    loading: 'ലോഡ് ചെയ്യുന്നു...',
    noShopsNearby: 'അടുത്ത് കടകൾ കണ്ടെത്തിയില്ല',
    retry: 'വീണ്ടും ശ്രമിക്കുക',
    emergency: 'അടിയന്തരം',
    offers: 'ഓഫറുകൾ',
    userDesc: 'അടുത്തുള്ള സേവനങ്ങൾ കണ്ടെത്തുക',
    providerDesc: 'നിങ്ങളുടെ ബിസിനസ്സ് വളർത്തുക',
    searchLanguage: 'ഭാഷ തിരയുക...',
  },
  or: {
    ...base,
    appTagline: 'ପ୍ରତ୍ୟେକ ଦୋକାନ, ପ୍ରତ୍ୟେକ ସେବା – ଏକ ସ୍ଥାନରେ',
    selectLanguage: 'ଭାଷା ବାଛନ୍ତୁ',
    continue: 'ଜାରି ରଖନ୍ତୁ',
    greeting_morning: 'ସୁପ୍ରଭାତ',
    greeting_afternoon: 'ନମସ୍କାର',
    nearbyServices: 'ନିକଟ ସେବାଗୁଡ଼ିକ',
    categories: 'ବିଭାଗ',
    callNow: 'କଲ',
    sendOtp: 'OTP ପଠାନ୍ତୁ',
    verifyLogin: 'ଯାଞ୍ଚ କରନ୍ତୁ',
    iAm: 'ମୁଁ',
    customer: 'ଗ୍ରାହକ',
    provider: 'ସେବା ପ୍ରଦାନକାରୀ',
    fullName: 'ପୂର୍ଣ ନାମ',
    phoneNumber: 'ଫୋନ ନମ୍ବର',
    logout: 'ଲଗ ଆଉଟ',
    loading: 'ଲୋଡ ହେଉଛି...',
    noShopsNearby: 'ନିକଟରେ ଦୋକାନ ମିଳିଲା ନାହିଁ',
    retry: 'ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ',
    emergency: 'ଜରୁରୀ',
    searchLanguage: 'ଭାଷା ଖୋଜନ୍ତୁ...',
  },
  as: {
    ...base,
    appTagline: 'প্ৰতিটো দোকান, প্ৰতিটো সেৱা – এটাই ঠাইত',
    selectLanguage: 'ভাষা বাছনি কৰক',
    continue: 'অব্যাহত ৰাখক',
    greeting_morning: 'শুভ ৰাতিপুৱা',
    greeting_afternoon: 'নমস্কাৰ',
    nearbyServices: 'ওচৰৰ সেৱাসমূহ',
    categories: 'বিভাগসমূহ',
    callNow: 'কল',
    sendOtp: 'OTP পঠাওক',
    verifyLogin: 'নিশ্চিত কৰক',
    iAm: 'মই',
    customer: 'গ্ৰাহক',
    provider: 'সেৱা প্ৰদানকাৰী',
    fullName: 'সম্পূৰ্ণ নাম',
    phoneNumber: 'ফোন নম্বৰ',
    logout: 'লগ আউট',
    loading: 'লোড হৈছে...',
    noShopsNearby: 'ওচৰত দোকান পোৱা নগৈল',
    retry: 'পুনৰ চেষ্টা কৰক',
    emergency: 'জৰুৰীকালীন',
    searchLanguage: 'ভাষা বিচাৰক...',
  },
  ur: {
    ...base,
    appTagline: 'ہر دکان، ہر سروس – ایک جگہ',
    selectLanguage: 'زبان منتخب کریں',
    continue: 'جاری رکھیں',
    greeting_morning: 'صبح بخیر',
    greeting_afternoon: 'السلام علیکم',
    greeting_evening: 'شام بخیر',
    nearbyServices: 'قریبی خدمات',
    categories: 'زمرے',
    callNow: 'کال',
    sendOtp: 'OTP بھیجیں',
    verifyLogin: 'تصدیق کریں',
    customer: 'گاہک',
    provider: 'خدمت فراہم کنندہ',
    fullName: 'پورا نام',
    phoneNumber: 'فون نمبر',
    logout: 'لاگ آؤٹ',
    loading: 'لوڈ ہو رہا ہے...',
    emergency: 'ہنگامی',
    searchLanguage: 'زبان تلاش کریں...',
  },
  ne: {
    ...base,
    appTagline: 'हर पसल, हर सेवा – एउटै ठाउँमा',
    selectLanguage: 'भाषा छान्नुस्',
    continue: 'जारी राख्नुस्',
    greeting_morning: 'सुप्रभात',
    greeting_afternoon: 'नमस्ते',
    nearbyServices: 'नजिकका सेवाहरू',
    categories: 'श्रेणीहरू',
    callNow: 'कल',
    sendOtp: 'OTP पठाउनुस्',
    verifyLogin: 'प्रमाणित गर्नुस्',
    customer: 'ग्राहक',
    provider: 'सेवा प्रदायक',
    fullName: 'पूरा नाम',
    phoneNumber: 'फोन नम्बर',
    logout: 'लग आउट',
    loading: 'लोड हुँदैछ...',
    emergency: 'आपतकाल',
    searchLanguage: 'भाषा खोज्नुस्...',
  },
  sa: {
    ...base,
    appTagline: 'सर्वं दुकानं, सर्वा सेवा – एकत्र',
    selectLanguage: 'भाषां चिनुत',
    continue: 'अग्रे गच्छत',
    greeting_morning: 'सुप्रभातम्',
    greeting_afternoon: 'नमस्ते',
    nearbyServices: 'समीपसेवाः',
    categories: 'श्रेणयः',
    callNow: 'आह्वयत',
    sendOtp: 'OTP प्रेषयत',
    verifyLogin: 'प्रमाणयत',
    customer: 'क्रेता',
    provider: 'सेवादाता',
    fullName: 'पूर्णनाम',
    phoneNumber: 'दूरभाषसंख्या',
    logout: 'निर्गमनम्',
    loading: 'लोडयति...',
    emergency: 'आपत्कालः',
    searchLanguage: 'भाषां अन्विष्यत...',
  },
  sd: {
    ...base,
    appTagline: 'هر دڪان، هر خدمت – هڪ هنڌ',
    selectLanguage: 'ٻولي چونڊيو',
    continue: 'جاري رکو',
    callNow: 'ڪال',
    customer: 'گراهڪ',
    provider: 'خدمت ڏيندڙ',
    emergency: 'هنگامي',
    searchLanguage: 'ٻولي ڳوليو...',
  },
  doi: {
    ...base,
    appTagline: 'हर दुकान, हर सेवा – इक थाह',
    selectLanguage: 'भाशा चुनो',
    continue: 'अग्गे जाओ',
    callNow: 'काल',
    customer: 'ग्राहक',
    provider: 'सेवा देणआला',
    emergency: 'आपात',
    searchLanguage: 'भाशा खोजो...',
  },
  mai: {
    ...base,
    appTagline: 'हर दोकान, हर सेवा – एक ठाम',
    selectLanguage: 'भाषा चुनू',
    continue: 'आगू बढ़ू',
    callNow: 'कॉल',
    customer: 'ग्राहक',
    provider: 'सेवा प्रदाता',
    emergency: 'आपातकाल',
    searchLanguage: 'भाषा खोजू...',
  },
  sat: {
    ...base,
    appTagline: 'ᱦᱟᱨ ᱫᱩᱠᱟᱱ, ᱦᱟᱨ ᱥᱮᱵᱟ – ᱢᱤᱫ ᱡᱟᱭᱜᱟ',
    selectLanguage: 'ᱵᱷᱟᱥᱟ ᱧᱮᱞ',
    continue: 'ᱦᱩᱭᱩᱜ ᱠᱟᱱᱟ',
    callNow: 'ᱠᱚᱞ',
    customer: 'ᱜᱟᱦᱟᱠ',
    provider: 'ᱥᱮᱵᱟ ᱫᱮᱜᱟ',
    emergency: 'ᱟᱲᱟᱝ',
    searchLanguage: 'ᱵᱷᱟᱥᱟ ᱧᱮᱞ...',
  },
};

export const LANGUAGES = [
  { code: 'en',  name: 'English',    nativeName: 'English',      flag: '🇬🇧', gradient: 'linear-gradient(135deg,#1a2a4a,#0d1a33)' },
  { code: 'hi',  name: 'Hindi',      nativeName: 'हिंदी',         flag: '🇮🇳', gradient: 'linear-gradient(135deg,#2a1a0a,#1a0a00)' },
  { code: 'mr',  name: 'Marathi',    nativeName: 'मराठी',         flag: '🟠',  gradient: 'linear-gradient(135deg,#2a1500,#1a0d00)' },
  { code: 'gu',  name: 'Gujarati',   nativeName: 'ગુજરાતી',       flag: '🟡',  gradient: 'linear-gradient(135deg,#2a2200,#1a1600)' },
  { code: 'pa',  name: 'Punjabi',    nativeName: 'ਪੰਜਾਬੀ',        flag: '🟣',  gradient: 'linear-gradient(135deg,#1e0a2a,#120518)' },
  { code: 'bn',  name: 'Bengali',    nativeName: 'বাংলা',         flag: '🟢',  gradient: 'linear-gradient(135deg,#0a2a10,#051508)' },
  { code: 'ta',  name: 'Tamil',      nativeName: 'தமிழ்',         flag: '🔴',  gradient: 'linear-gradient(135deg,#2a0a0a,#180505)' },
  { code: 'te',  name: 'Telugu',     nativeName: 'తెలుగు',        flag: '🔵',  gradient: 'linear-gradient(135deg,#0a1a2a,#050d18)' },
  { code: 'kn',  name: 'Kannada',    nativeName: 'ಕನ್ನಡ',         flag: '🟤',  gradient: 'linear-gradient(135deg,#1a1000,#0d0800)' },
  { code: 'ml',  name: 'Malayalam',  nativeName: 'മലയാളം',        flag: '⚫',  gradient: 'linear-gradient(135deg,#0a0a1a,#050510)' },
  { code: 'or',  name: 'Odia',       nativeName: 'ଓଡ଼ିଆ',         flag: '🟥',  gradient: 'linear-gradient(135deg,#2a0a00,#180500)' },
  { code: 'as',  name: 'Assamese',   nativeName: 'অসমীয়া',       flag: '🟦',  gradient: 'linear-gradient(135deg,#001a2a,#000d18)' },
  { code: 'ur',  name: 'Urdu',       nativeName: 'اردو',          flag: '🇵🇰', gradient: 'linear-gradient(135deg,#001a00,#000d00)' },
  { code: 'ne',  name: 'Nepali',     nativeName: 'नेपाली',         flag: '🇳🇵', gradient: 'linear-gradient(135deg,#2a0010,#180008)' },
  { code: 'sa',  name: 'Sanskrit',   nativeName: 'संस्कृत',        flag: '🕉️', gradient: 'linear-gradient(135deg,#1a1a00,#0d0d00)' },
  { code: 'sd',  name: 'Sindhi',     nativeName: 'سنڌي',          flag: '🟫',  gradient: 'linear-gradient(135deg,#1a0a00,#0d0500)' },
  { code: 'doi', name: 'Dogri',      nativeName: 'डोगरी',          flag: '🏔️', gradient: 'linear-gradient(135deg,#0a0a2a,#050518)' },
  { code: 'mai', name: 'Maithili',   nativeName: 'मैथिली',         flag: '🌸',  gradient: 'linear-gradient(135deg,#2a0a1a,#180510)' },
  { code: 'sat', name: 'Santali',    nativeName: 'ᱥᱟᱱᱛᱟᱲᱤ',      flag: '🌿',  gradient: 'linear-gradient(135deg,#002a10,#001808)' },
  { code: 'ks',  name: 'Kashmiri',   nativeName: 'کشمیری',         flag: '❄️',  gradient: 'linear-gradient(135deg,#001a2a,#000d18)' },
  { code: 'kok', name: 'Konkani',    nativeName: 'कोंकणी',         flag: '🌊',  gradient: 'linear-gradient(135deg,#001a1a,#000d0d)' },
];

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => localStorage.getItem('nikat_lang') || null);

  const setLanguage = (code) => {
    localStorage.setItem('nikat_lang', code);
    setLanguageState(code);
  };

  const t = (key) => {
    const lang = language || 'en';
    return translations[lang]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
