import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    appTagline: 'Nearest Services, Instantly',
    selectLanguage: 'Select Language',
    chooseLanguage: 'Choose your preferred language',
    continue: 'Continue',
    greeting_morning: 'Good morning',
    greeting_afternoon: 'Good afternoon',
    greeting_evening: 'Good evening',
    nearbyServices: 'Nearby Services',
    searchPlaceholder: 'Search services, shops...',
    categories: 'Categories',
    allCategories: 'All',
    subscribeToUnlock: 'Subscribe to unlock',
    unlockToContact: 'Unlock to Contact',
    callNow: 'Call',
    whatsapp: 'WhatsApp',
    directions: 'Directions',
    bookService: 'Book Service',
    reviews: 'Reviews',
    services: 'Services',
    sendOtp: 'Send OTP',
    verifyLogin: 'Verify & Login',
    iAm: 'I am a',
    customer: 'Customer',
    provider: 'Provider',
    fullName: 'Full Name',
    phoneNumber: 'Phone Number',
    enterOtp: 'Enter OTP',
    myProfile: 'My Profile',
    logout: 'Logout',
    subscribe: 'Subscribe',
    choosePlan: 'Choose a Plan',
    unlockFullAccess: 'Unlock Full Access',
    aadhaarVerification: 'Aadhaar Verification',
    enterAadhaar: 'Enter Aadhaar Number',
    verifyAadhaar: 'Verify Aadhaar',
    shopDetails: 'Shop Details',
    setupStore: 'Setup Store',
    createStore: 'Create Store',
    shopName: 'Shop Name',
    category: 'Category',
    description: 'Description',
    location: 'Location',
    useGps: 'Use GPS',
    openNow: 'Open Now',
    closed: 'Closed',
    negotiable: 'Negotiable',
    back: 'Back',
    cancel: 'Cancel',
    confirm: 'Confirm',
    loading: 'Loading...',
    noShopsNearby: 'No shops found nearby',
    internetCheck: 'Check your internet connection',
    retry: 'Retry',
  },
  hi: {
    appTagline: 'नज़दीकी सेवाएं, तुरंत',
    selectLanguage: 'भाषा चुनें',
    chooseLanguage: 'अपनी पसंदीदा भाषा चुनें',
    continue: 'जारी रखें',
    greeting_morning: 'सुप्रभात',
    greeting_afternoon: 'नमस्ते',
    greeting_evening: 'शुभ संध्या',
    nearbyServices: 'नज़दीकी सेवाएं',
    searchPlaceholder: 'सेवाएं, दुकान खोजें...',
    categories: 'श्रेणियां',
    allCategories: 'सभी',
    subscribeToUnlock: 'अनलॉक के लिए सब्सक्राइब करें',
    unlockToContact: 'संपर्क अनलॉक करें',
    callNow: 'कॉल करें',
    whatsapp: 'व्हाट्सएप',
    directions: 'दिशा',
    bookService: 'बुक करें',
    reviews: 'समीक्षाएं',
    services: 'सेवाएं',
    sendOtp: 'OTP भेजें',
    verifyLogin: 'वेरिफाई करें',
    iAm: 'मैं हूं',
    customer: 'ग्राहक',
    provider: 'सेवा प्रदाता',
    fullName: 'पूरा नाम',
    phoneNumber: 'फ़ोन नंबर',
    enterOtp: 'OTP दर्ज करें',
    myProfile: 'मेरी प्रोफाइल',
    logout: 'लॉग आउट',
    subscribe: 'सब्सक्राइब',
    choosePlan: 'प्लान चुनें',
    unlockFullAccess: 'पूरी पहुंच अनलॉक करें',
    aadhaarVerification: 'आधार सत्यापन',
    enterAadhaar: 'आधार नंबर दर्ज करें',
    verifyAadhaar: 'आधार सत्यापित करें',
    shopDetails: 'दुकान विवरण',
    setupStore: 'दुकान सेटअप',
    createStore: 'दुकान बनाएं',
    shopName: 'दुकान का नाम',
    category: 'श्रेणी',
    description: 'विवरण',
    location: 'स्थान',
    useGps: 'GPS उपयोग करें',
    openNow: 'अभी खुला',
    closed: 'बंद',
    negotiable: 'बातचीत योग्य',
    back: 'वापस',
    cancel: 'रद्द करें',
    confirm: 'पुष्टि करें',
    loading: 'लोड हो रहा है...',
    noShopsNearby: 'नज़दीक कोई दुकान नहीं मिली',
    internetCheck: 'इंटरनेट कनेक्शन जांचें',
    retry: 'पुनः प्रयास',
  },
  mr: {
    appTagline: 'जवळच्या सेवा, त्वरित',
    selectLanguage: 'भाषा निवडा',
    chooseLanguage: 'तुमची पसंतीची भाषा निवडा',
    continue: 'पुढे जा',
    greeting_morning: 'सुप्रभात',
    greeting_afternoon: 'नमस्कार',
    greeting_evening: 'शुभ संध्याकाळ',
    nearbyServices: 'जवळच्या सेवा',
    searchPlaceholder: 'सेवा, दुकान शोधा...',
    categories: 'श्रेण्या',
    allCategories: 'सर्व',
    subscribeToUnlock: 'अनलॉक करण्यासाठी सदस्यता घ्या',
    unlockToContact: 'संपर्क अनलॉक करा',
    callNow: 'कॉल करा',
    whatsapp: 'व्हाट्सअप',
    directions: 'दिशा',
    bookService: 'बुक करा',
    reviews: 'समीक्षा',
    services: 'सेवा',
    sendOtp: 'OTP पाठवा',
    verifyLogin: 'सत्यापित करा',
    iAm: 'मी आहे',
    customer: 'ग्राहक',
    provider: 'सेवा प्रदाता',
    fullName: 'पूर्ण नाव',
    phoneNumber: 'फोन नंबर',
    enterOtp: 'OTP प्रविष्ट करा',
    myProfile: 'माझी प्रोफाइल',
    logout: 'लॉग आउट',
    subscribe: 'सदस्यता घ्या',
    choosePlan: 'प्लान निवडा',
    unlockFullAccess: 'पूर्ण प्रवेश अनलॉक करा',
    aadhaarVerification: 'आधार सत्यापन',
    enterAadhaar: 'आधार क्रमांक प्रविष्ट करा',
    verifyAadhaar: 'आधार सत्यापित करा',
    shopDetails: 'दुकान तपशील',
    setupStore: 'दुकान सेटअप',
    createStore: 'दुकान तयार करा',
    shopName: 'दुकानाचे नाव',
    category: 'श्रेणी',
    description: 'वर्णन',
    location: 'स्थान',
    useGps: 'GPS वापरा',
    openNow: 'आता उघडे',
    closed: 'बंद',
    negotiable: 'वाटाघाटी योग्य',
    back: 'मागे',
    cancel: 'रद्द करा',
    confirm: 'पुष्टी करा',
    loading: 'लोड होत आहे...',
    noShopsNearby: 'जवळ कोणतेही दुकान सापडले नाही',
    internetCheck: 'इंटरनेट कनेक्शन तपासा',
    retry: 'पुन्हा प्रयत्न करा',
  },
  gu: {
    appTagline: 'નજીકની સેવાઓ, તરત',
    selectLanguage: 'ભાષા પસંદ કરો',
    chooseLanguage: 'તમારી પસંદીદા ભાષા પસંદ કરો',
    continue: 'આગળ વધો',
    greeting_morning: 'સુપ્રભાત',
    greeting_afternoon: 'નમસ્તે',
    greeting_evening: 'શુભ સંધ્યા',
    nearbyServices: 'નજીકની સેવાઓ',
    searchPlaceholder: 'સેવાઓ, દુકાન શોધો...',
    categories: 'શ્રેણીઓ',
    allCategories: 'બધા',
    subscribeToUnlock: 'અનલૉક કરવા સબ્સ્ક્રાઇબ કરો',
    unlockToContact: 'સંપર્ક અનલૉક કરો',
    callNow: 'કૉલ',
    whatsapp: 'વ્હૉટ્સએપ',
    directions: 'દિશા',
    bookService: 'બુક કરો',
    reviews: 'સમીક્ષાઓ',
    services: 'સેવાઓ',
    sendOtp: 'OTP મોકલો',
    verifyLogin: 'ચકાસો',
    iAm: 'હું છું',
    customer: 'ગ્રાહક',
    provider: 'સેવા પ્રદાતા',
    fullName: 'પૂરું નામ',
    phoneNumber: 'ફોન નંબર',
    enterOtp: 'OTP દાખલ કરો',
    myProfile: 'મારી પ્રોફાઇલ',
    logout: 'લૉગ આઉટ',
    subscribe: 'સબ્સ્ક્રાઇબ',
    choosePlan: 'પ્લાન પસંદ કરો',
    unlockFullAccess: 'સંપૂર્ણ ઍક્સેસ અનલૉક કરો',
    aadhaarVerification: 'આધાર ચકાસણી',
    enterAadhaar: 'આધાર નંબર દાખલ કરો',
    verifyAadhaar: 'આધાર ચકાસો',
    shopDetails: 'દુકાન વિગતો',
    setupStore: 'દુકાન સેટઅપ',
    createStore: 'દુકાન બનાવો',
    shopName: 'દુકાનનું નામ',
    category: 'શ્રેણી',
    description: 'વર્ણન',
    location: 'સ્થાન',
    useGps: 'GPS વાપરો',
    openNow: 'હવે ખુલ્લું',
    closed: 'બંધ',
    negotiable: 'વાટાઘાટ',
    back: 'પાછળ',
    cancel: 'રદ કરો',
    confirm: 'પુષ્ટિ',
    loading: 'લોડ થઈ રહ્યું છે...',
    noShopsNearby: 'નજીક કોઈ દુકાન મળી નથી',
    internetCheck: 'ઈન્ટરનેટ કનેક્શન તપાસો',
    retry: 'ફરી પ્રયાસ',
  },
  te: {
    appTagline: 'దగ్గర సేవలు, వెంటనే',
    selectLanguage: 'భాష ఎంచుకోండి',
    chooseLanguage: 'మీకు నచ్చిన భాష ఎంచుకోండి',
    continue: 'కొనసాగించండి',
    greeting_morning: 'శుభోదయం',
    greeting_afternoon: 'నమస్కారం',
    greeting_evening: 'శుభ సాయంత్రం',
    nearbyServices: 'దగ్గర సేవలు',
    searchPlaceholder: 'సేవలు, దుకాణాలు వెతకండి...',
    categories: 'వర్గాలు',
    allCategories: 'అన్నీ',
    subscribeToUnlock: 'అన్‌లాక్ చేయడానికి సభ్యత్వం తీసుకోండి',
    unlockToContact: 'సంప్రదించడానికి అన్‌లాక్ చేయండి',
    callNow: 'కాల్',
    whatsapp: 'వాట్సాప్',
    directions: 'దిశలు',
    bookService: 'బుక్ చేయండి',
    reviews: 'సమీక్షలు',
    services: 'సేవలు',
    sendOtp: 'OTP పంపండి',
    verifyLogin: 'నిర్ధారించండి',
    iAm: 'నేను',
    customer: 'కస్టమర్',
    provider: 'సేవా ప్రదాత',
    fullName: 'పూర్తి పేరు',
    phoneNumber: 'ఫోన్ నంబర్',
    enterOtp: 'OTP నమోదు చేయండి',
    myProfile: 'నా ప్రొఫైల్',
    logout: 'లాగ్ అవుట్',
    subscribe: 'సభ్యత్వం',
    choosePlan: 'ప్లాన్ ఎంచుకోండి',
    unlockFullAccess: 'పూర్తి యాక్సెస్ అన్‌లాక్',
    aadhaarVerification: 'ఆధార్ ధృవీకరణ',
    enterAadhaar: 'ఆధార్ నంబర్ నమోదు చేయండి',
    verifyAadhaar: 'ఆధార్ ధృవీకరించండి',
    shopDetails: 'దుకాణ వివరాలు',
    setupStore: 'దుకాణం సెటప్',
    createStore: 'దుకాణం సృష్టించండి',
    shopName: 'దుకాణం పేరు',
    category: 'వర్గం',
    description: 'వివరణ',
    location: 'స్థానం',
    useGps: 'GPS వాడండి',
    openNow: 'ఇప్పుడు తెరిచి ఉంది',
    closed: 'మూసివేయబడింది',
    negotiable: 'సంప్రదింపు',
    back: 'వెనుకకు',
    cancel: 'రద్దు',
    confirm: 'నిర్ధారించు',
    loading: 'లోడ్ అవుతోంది...',
    noShopsNearby: 'దగ్గర దుకాణాలు కనుగొనబడలేదు',
    internetCheck: 'ఇంటర్నెట్ కనెక్షన్ తనిఖీ చేయండి',
    retry: 'మళ్ళీ ప్రయత్నించండి',
  },
};

const LANGUAGES = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिंदी', flag: '🇮🇳' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', flag: '🟠' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', flag: '🟡' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', flag: '🔵' },
];

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => localStorage.getItem('nikat_lang') || null);

  const setLanguage = (code) => {
    localStorage.setItem('nikat_lang', code);
    setLanguageState(code);
  };

  const t = (key) => {
    if (!language) return translations.en[key] || key;
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
